// Import global CSS or Tailwind CSS styles
import '../styles/globals.css'; // Ensure the correct path to your global CSS file
import { Inter } from 'next/font/google'; // Optional: You can use Google Fonts

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

// Optional: Example of Google Font usage
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Apply font class globally */}
        {children}
      </body>
    </html>
  );
}
